AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: api-students-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: arn:aws:iam::218543369212:role/LabRole
      ContainerDefinitions:
        - Name: crud-api
          Image: 218543369212.dkr.ecr.us-east-1.amazonaws.com/api-students:latest
          PortMappings:
            - ContainerPort: 80

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref MyTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: [subnet-035e3ff7c26ab4421]
          SecurityGroups: [sg-040fc209e69bb5130]
          Subnets:
          - !Ref SubnetId
          SecurityGroups:
          - !Ref SecurityGroupId
